[package]
name = "helia"
version = "0.0.0"
edition = "2021"
description = "A Radiant Game Engine"
license = "MIT OR Apache-2.0"

[workspace]
members = [ "helia_internal", "examples/*" ]

[dependencies]
helia_internal = { path = "helia_internal" }